### ISSUE TITLE
docker限制特权容器权限

### ISSUE THREAD

**Issue by Detavern** [EasyTier/easytier.github.io#114]
[见原安装文档docker compose模式](https://github.com/EasyTier/easytier.github.io/blob/main/guide/installation.md)

```
  easytier:
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
    privileged: true
    mem_limit: 0m
    container_name: easytier
    hostname: easytier
    network_mode: host
    volumes:
      - /etc/easytier:/root
    environment:
      - TZ=Asia/Shanghai
    image: easytier/easytier:latest # 国内用户可以使用 m.daocloud.io/docker.io/easytier/easytier:latest
    command: -i <ip> --network-name <用户> --network-secret <密码> -p tcp://<服务器地址>:11010
```

是不是收紧为如下配置更好？
我自己试了两天，目前没有问题

```
  easytier:
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
    mem_limit: 0m
    container_name: easytier
    hostname: easytier
    network_mode: host

    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
   
    volumes:
      - /etc/easytier:/root
    environment:
      - TZ=Asia/Shanghai
    image: easytier/easytier:latest # 国内用户可以使用 m.daocloud.io/docker.io/easytier/easytier:latest
    command: -i <ip> --network-name <用户> --network-secret <密码> -p tcp://<服务器地址>:11010
```
